/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "forest-green": "#2A4034",
        "mint-green": "#A3D4C1",
        "stone": "#D1D5DB",
        "ochre": "#DDA74A",
        "charcoal": "#333333",
        "brand-red": "#E65C5C",
        "brand-yellow": "#F2D648",
        "brand-green": "#22574A",
        "brand-blue": "#2A7886",
        "light-yellow": "#F5F0BB",
        "light-green": "#C2D1A4",
        "teal": "#83AE9B",
        "blue-grey": "#6A8993",
        "light-cream": "#E3E1C4",
        "medium-green": "#688448",
        "dark-green": "#3E5725",
        "background-light": "#f5f8f6",
        "background-dark": "#102216",
        "brand-light-green": "#91C8B4",
        "brand-teal": "#2E8A99",
        "brand-cream": "#F0EAC5",
        "brand-orange": "#D9A05B",
        // Theme colors for forms
        primary: "#22574A",
        "primary-foreground": "#FFFFFF",
        "muted-foreground": "#6B7280",
        border: "#D1D5DB",
        input: "#D1D5DB",
        accent: "#DDA74A",
        "accent-foreground": "#333333",
        background: "#FFFFFF",
        foreground: "#1F2937",
      },
    },
  },
  plugins: [],
};